<Project>
  <PropertyGroup>
    <Version>1.5.2</Version>
    <AssemblyVersion>1.5.2.0</AssemblyVersion>
    <FileVersion>1.5.2.0</FileVersion>
    <Authors>sZIP contributors</Authors>
    <Product>sZIP</Product>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
