[LangOptions]
LanguageName=한국어
LanguageID=$0412
LanguageCodePage=949
DialogFontName=맑은 고딕
DialogFontSize=9
WelcomeFontName=맑은 고딕
WelcomeFontSize=12

[Messages]
SetupAppTitle=설치
SetupWindowTitle=%1 설치
UninstallAppTitle=제거
UninstallAppFullTitle=%1 제거
InformationTitle=정보
ConfirmTitle=확인
ErrorTitle=오류
ExitSetupTitle=설치 종료
ExitSetupMessage=설치가 완료되지 않았습니다. 지금 종료하면 프로그램이 설치되지 않습니다.%n%n설치를 종료하시겠습니까?
ButtonBack=< 뒤로(&B)
ButtonNext=다음(&N) >
ButtonInstall=설치(&I)
ButtonOK=확인
ButtonCancel=취소
ButtonYes=예(&Y)
ButtonYesToAll=모두 예(&A)
ButtonNo=아니요(&N)
ButtonNoToAll=모두 아니요(&O)
ButtonFinish=마침(&F)
ButtonBrowse=찾아보기(&B)...
ButtonWizardBrowse=찾아보기(&R)...
ButtonNewFolder=새 폴더 만들기(&M)
SelectLanguageTitle=설치 언어 선택
SelectLanguageLabel=설치에 사용할 언어를 선택하세요.
ClickNext=계속하려면 다음을, 설치를 끝내려면 취소를 클릭하세요.
BrowseDialogTitle=폴더 찾아보기
BrowseDialogLabel=목록에서 폴더를 선택한 뒤 확인을 클릭하세요.
NewFolderName=새 폴더
WelcomeLabel1=[name] 설치 마법사
WelcomeLabel2=[name/ver]을(를) 컴퓨터에 설치합니다.%n%n계속하기 전에 실행 중인 다른 프로그램을 닫는 것을 권장합니다.
WizardSelectDir=설치 위치 선택
SelectDirDesc=[name]을(를) 설치할 위치를 선택하세요.
SelectDirLabel3=다음 폴더에 [name]을(를) 설치합니다.
SelectDirBrowseLabel=계속하려면 다음을 클릭하세요. 다른 폴더를 선택하려면 찾아보기를 클릭하세요.
DiskSpaceGBLabel=최소 [gb]GB의 여유 공간이 필요합니다.
DiskSpaceMBLabel=최소 [mb]MB의 여유 공간이 필요합니다.
InvalidPath=드라이브 문자가 포함된 전체 경로를 입력하세요.
WizardSelectTasks=추가 작업 선택
SelectTasksDesc=설치하면서 수행할 추가 작업을 선택하세요.
SelectTasksLabel2=원하는 추가 작업을 선택한 뒤 다음을 클릭하세요.
WizardReady=설치 준비 완료
ReadyLabel1=설치를 시작하려면 설치를 클릭하세요. 설정을 확인하거나 변경하려면 뒤로를 클릭하세요.
ReadyLabel2a=설치를 시작하려면 설치를 클릭하세요.
ReadyMemoUserInfo=사용자 정보:
ReadyMemoDir=설치 위치:
ReadyMemoType=설치 유형:
ReadyMemoComponents=선택한 구성 요소:
ReadyMemoGroup=시작 메뉴 폴더:
ReadyMemoTasks=추가 작업:
WizardPreparing=설치 준비 중
PreparingDesc=[name] 설치를 준비하고 있습니다.
PreviousInstallNotCompleted=이전 설치 또는 제거 작업을 완료하려면 컴퓨터를 다시 시작해야 합니다.%n%n컴퓨터를 다시 시작한 뒤 설치를 다시 실행하세요.
WizardInstalling=설치 중
InstallingLabel=[name]을(를) 설치하는 동안 잠시 기다려 주세요.
FinishedHeadingLabel=[name] 설치 완료
FinishedLabelNoIcons=[name] 설치가 완료되었습니다.
FinishedLabel=[name] 설치가 완료되었습니다. 설치된 아이콘을 선택하여 프로그램을 실행할 수 있습니다.
ClickFinish=설치를 마치려면 마침을 클릭하세요.
FinishedRestartLabel=[name] 설치를 완료하려면 컴퓨터를 다시 시작해야 합니다. 지금 다시 시작하시겠습니까?
FinishedRestartMessage=[name] 설치를 완료하려면 컴퓨터를 다시 시작해야 합니다.%n%n지금 다시 시작하시겠습니까?
StatusClosingApplications=프로그램을 닫는 중...
StatusCreateDirs=폴더를 만드는 중...
StatusExtractFiles=파일을 푸는 중...
StatusCreateIcons=바로가기를 만드는 중...
StatusCreateRegistryEntries=시스템 설정을 등록하는 중...
StatusRegisterFiles=파일을 등록하는 중...
StatusSavingUninstall=제거 정보를 저장하는 중...
StatusRunProgram=설치를 마무리하는 중...
StatusRestartingApplications=프로그램을 다시 시작하는 중...
StatusRollback=변경 사항을 되돌리는 중...
ErrorChangingAttr=파일 속성을 변경하는 중 오류가 발생했습니다.
ErrorCreatingDir=폴더를 만들 수 없습니다: "%1"
ErrorTooManyFilesInDir=폴더에 파일이 너무 많아 파일을 만들 수 없습니다: "%1"
SourceIsCorrupted=원본 파일이 손상되었습니다.
SourceDoesntExist=원본 파일이 없습니다.
ErrorReadingExistingDest=기존 파일을 읽는 중 오류가 발생했습니다.
FileExistsSelectAction=파일이 이미 있습니다.%n%n원하는 작업을 선택하세요.
ConfirmUninstall=컴퓨터에서 %1을(를) 제거하시겠습니까?
UninstallOnlyOnWin64=이 프로그램은 64비트 Windows에서만 제거할 수 있습니다.
UninstallStatusLabel=%1을(를) 제거하는 동안 잠시 기다려 주세요.
UninstalledAll=%1 제거가 완료되었습니다.
UninstalledMost=%1 제거가 완료되었습니다.%n%n일부 항목은 직접 삭제해야 합니다.
